name: ci

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test-env
          environment-file: environment-cpu.yml
          python-version: 3.9
          auto-activate-base: false

      - name: install deeprank-gnn-esm
        run: pip install .

      - name: install test dependencies
        run: pip install pytest pytest-cov coverage hypothesis

      - name: run tests
        run: >-
          pytest --cov
          --cov-report xml:coverage.xml
          --cov-append
          -vv
          --hypothesis-show-statistics

      - uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699
        if: >-
          ${{ github.event_name != 'pull_request' ||
          github.event.pull_request.head.repo.full_name == github.repository }}
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage.xml
